### ISSUE TITLE
ImportError: No module named IN

### ISSUE THREAD

**Issue by HamAndChris** [ddetommaso/tobiiglasses-controller#4]
Running this on Windows with 64-bit Anaconda 2.7, I get the following error message:

```
Traceback (most recent call last):
  File "connect.py", line 18, in <module>
    from tobiiglassesctrl.controller import TobiiGlassesController
  File "C:\ProgramData\Anaconda2\lib\site-packages\tobiiglassesctrl\controller.py", line 29, in <module>
    import IN
ImportError: No module named IN
```

It seems to be a somewhat common problem. The module is only used on line 110 (__mksock__) to import a constant, so it could easily be replaced with the numeric value which is 25.
```
try:
	if iptype == socket.AF_INET6 and sys.platform == "linux2":
		sock.setsockopt(socket.SOL_SOCKET, IN.SO_BINDTODEVICE, self.iface_name+'\0')
```

**Comment by ddetommaso** [comment]
Hi @HamAndChris,

thank you for reporting this issue.
I modified the code to import the module IN only in linux systems, so it should work fine for you and other Windows systems as well.

Please download and check the updated version 2.0.2.

Best,
