### ISSUE TITLE
One more function to add

### ISSUE THREAD

**Issue by HamAndChris** [ddetommaso/tobiiglasses-controller#6]
Hi, this gets a list of all recordings, which I am using to find the most recent one:

```
	def get_recordings(self):
		return self.__get_request__('/api/recordings')
```

Thanks,
- Chris

_Originally posted by @HamAndChris in https://github.com/ddetommaso/tobiiglasses-controller/issues/5#issuecomment-454538868_

**Comment by ddetommaso** [comment]
I've just committed the change adding the method!
Thank you for your work!
